cli:
  cloud_img_url: "https://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.img"
  app_home_dir: ".myapp" 
  runserver:
    port: 11000
  sync:
    port: 912000
  uuid: 99d6925e-1123-44e9-b575-672a33f93a5a
